#!/bin/bash

python3 -m venv myenv
python3 -m pip install --upgrade pip
source myenv/bin/activate
pip install -r requirements.txt
python manage.py migrate
python manage.py createsuperuser --username=admin --email=admin@example.com
python manage.py loaddata books
python manage.py runserver
