# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('ISBN', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 9, 17, 40, 274727, tzinfo=utc))),
            ],
        ),
    ]
