# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('status_code', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('uri', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 17, 47, 41, 218930, tzinfo=utc)),
        ),
    ]
