# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180726_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 19, 14, 16, 104343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 19, 14, 16, 103176, tzinfo=utc)),
        ),
    ]
